New-Item -Path ../chap05 -Name "5.3_gray2color_image_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_accumulate_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_accumulate_example2.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_append_components_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_binary_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_cast_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_change_information_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_extract_componints_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_logic_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_mathematics_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_reslice_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_reslice_example2.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_shrink_3d_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_image_shrink_magnify_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_visit_image_pixel_directly_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.3_visit_image_pixel_iteratively_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.4_canny_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.4_image_gradient_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.4_laplacian_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.4_sobel_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.5_anistropic_filter_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.5_gaussian_filter_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.5_mean_filter_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.5_median_filter_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.6_butterworth_high_pass_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.6_butterworth_low_pass_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.6_fft_and_rfft_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.6_ideal_high_pass_example.cpp" -ItemType file
New-Item -Path ../chap05 -Name "5.6_ideal_low_pass_example.cpp" -ItemType file
